---
title: "Data frame"
output: html_document
---

## Data frame
> 2차원 구조를 가져 행렬과 동일한 형태를 보이지만 각 열이 서로 다른 데이터 유형을 가질 수 있다.

### Data frame 생성
```{r}
a <- c(1,2,3,4)
b <- c('Apple','Banana','Peach','Berry')
c <- c(5,2,7,9)
d <- c(500,200,200,500)
fruit <- data.frame(a, b, c, d)
str(fruit)
fruit # 벡터 이름을 변수 이름으로 사용
```
> 각 vector가 Data frame의 열을 구성하며 이를 변수(variable)이라고 부른다.

```{r}
fruit <- data.frame(no=a,name=b,qty=c,price=d)
fruit # 직접 변수 이름 지정 가능
```

rbind(), cbind()
```{r}
add_fruit <- data.frame(count=c(1,2,3,4))
fruit <- cbind(fruit, add_fruit)
fruit
```
> 추가하고자 하는 열을 data frame으로 만들어 cbind() 함수를 이용하여 기존의 data frame에 추가

as.data.frame()
```{r}
mat <- matrix(c(1,3,5,7,9,
                3,4,5,8,10,
                4,5,6,9,13), ncol=3)
mat
as.data.frame(mat)
make_name <- as.data.frame(mat)
colnames(make_name) <- c("one","two","three")
make_name
```

### Data frame indexing
```{r}
fruit[1,]
fruit[-1,] # 1행 빼고 출력
fruit[,2]
fruit[,3]
fruit[,3, drop=F] # drop=F로 형식 유지
fruit[, c(3,4)]
fruit[3,2]
fruit[3,1]
fruit[,3]
fruit$qty
fruit[[3]]
fruit[3]  # 데이터프레임 형식 유지
str(fruit$qty)
str(fruit[3])
```
> 행렬과 리스트에서 사용하는 indexing 기법을 그대로 사용 가능

### Data frame exam
```{r}
english <- c(90, 80, 60, 70)
math <- c(50, 60, 100, 20)
classnum <- c(1,1,2,2)
df_midterm <- data.frame(
  english, math, classnum)
df_midterm
str(df_midterm)
colnames(df_midterm)
rownames(df_midterm)
names(df_midterm)
mean(df_midterm$english)
mean(df_midterm$math)
```

```{r}
df_midterm2 <- data.frame(
  c(90, 80, 60, 70), 
  c(50, 60, 100, 20), 
  c(1,1,2,2))
colnames(df_midterm2)
rownames(df_midterm2)
names(df_midterm2)
df_midterm2
df_midterm2 <- data.frame(
  영어=c(90, 80, 60, 70), 
  수학=c(50, 60, 100, 20), 
  클래스=c(1,1,2,2))
df_midterm2
df_midterm2$영어
```

```{r}
#df <- data.frame(var1=c(4,3,8),var2=c(2,6)) # 오류
df <- data.frame(var1=c(4,3,8), 
                 var2=c(2,6,1))
str(df)
df$var_sum <- df$var1 + df$var2 #df$var_sum => 파생변수
df$var_mean <- df$var_sum/2
df$result <- ifelse(df$var1>df$var2, 
                    "var1이 크다", "var1이 작다")
df # df$var_sum, df$var_mean, var$result 추가
```

