---
title: "for(), while(), repeat()"
output: html_document
---

## 반복문
> 조건에 따라 특정 실행문을 지정된 횟수만큼 반복적으로 수행

### for()
> for(변수 in 변수) {실행문}

> 지정한 횟수만큼 실행문을 반복 수행

```{r}
for(data in LETTERS) 
  print(data)

for(data in LETTERS) 
  cat(data) # "\n"으로 개행처리 가능
```

```{r}
sum <- 0
for(i in 5:15){
  if(i%%10==0){
    break
  }
  sum <- sum + i
  print(paste(i,":",sum))
} # break를 통해 10에서 멈춤
```

```{r}
sum <-0
for(i in 5:15){
  if(i%%10==0){
    next;  #continue
  }
  sum <- sum + i
  print(paste(i,":",sum))
} # 조건에 해당하는 10 빼고 모두 출력
```

### while()
> while(조건) {실행문}

> for()와 동일한 방식으로 수행되는데 for()는 반복 횟수를 결정하는 변수를 사용하는 대신 while()은 증감식을 이용하여 반복 횟수를 지정

```{r}
sumNumber <- 0
while(sumNumber <= 20) { 
  i <- sample(1:5, 1) 
  sumNumber <-sumNumber+i; 
  cat(sumNumber,"\n")
} 
```



### repeat()
> 실행문내에서 break에 해당할때까지 계속 실행됨

```{r}
sumNumber <- 0
repeat { 
  i <- sample(1:5, 1) 
  sumNumber <-sumNumber+i; 
  cat(sumNumber,"\n")
  if(sumNumber > 20)
    break;
}
```

### exam

```{r}
# 구구단
for(dan in 1:9){
  for(num in 1:9){
    cat(dan,"x",num,"=",dan*num,"\t") # \n : 개행문자, \t : 탭문자
  }
  cat("\n")
}
```

```{r}
i<-1
while(i <= 10){
  cat(i,"\n")
  i <- i+1
}
cat("종료 후 :",i,"\n")
```

