---
title: "조건문"
output: html_document
---

## 조건문
> R에서는 if(),ifelse(),switch(),which() 함수를 이용해서 조건문을 작성할 수 있다.

### if()
> if(조건식){참인 경우 처리문}
  else{거짓인 경우 처리문}
  
> if(첫 번째 조건식){참인 경우 처리문}
  else if(두 번째 조건식){참인 경우 처리문}
  else{모든 조건에 만족하지 못한 경우 처리문}
  
```{r}
randomNum <-sample(1:20,1) # 1~10 숫자 한 개를 무작위로 추출
if(randomNum>10){
  cat(randomNum,":10보다 큽니다.","\n")
}else{
  cat(randomNum,":10보다 작거나 같습니다.","\n")
}
```

```{r}
if(randomNum%%2 == 1){
  cat(randomNum,";홀수","\n")
}else{
  cat(randomNum,";짝수","\n")
}
```

```{r}
score <- sample(0:100, 1)  # 0~100 숫자 한 개를 무작위로 추출
if (score >=90){
  cat(score,"는 A등급입니다","\n")
}else if (score >=80){
  cat(score,"는 B등급입니다","\n")
}else if (score >=70){
  cat(score,"는 C등급입니다","\n")
}else if (score >=60){
  cat(score,"는 D등급입니다","\n")
}else {
  cat(score,"는 F등급입니다","\n")
}
```

### ifelse()
> ifelse(조건식, 참인 경우 처리문, 거짓인 경우 처리문)

> 조건식이 참인 경우와 거짓인 경우 처리할 문장을 각각 작성한 후 조건식 결과에 따라서 처리문 실행 

```{r}
score <- sample(0:100, 1)  # 0~100 숫자 한 개를 무작위로 추출
score
ifelse(score >= 60, "P", "F")

```

### switch()
> switch(비교문, 실행문1,실행문2,실행문3...)

```{r}
month <- sample(1:12,1)
month <- paste(month,"월",sep="") 
result <- switch(month,
                 "12월"=,"1월"=,"2월"="겨울",
                 "3월"=,"4월"=,"5월"="봄",
                 "6월"=,"7월"=,"8월"="여름",
                 "가을")
cat(month,"은 ",result,"입니다\n",sep="")
```

```{r}
num <- sample(1:10,1)
num
switch(num,"A","B","C","D") #"A"부터 1,2,3,4 / 5부터는 출력되지 않음
```

### which()
> which(조건식)

> 특정 데이터를 검색하는 함수로 조건식에 만족하는 경우 해당 인덱스를 출력

```{r}
name <- c("shin", "kim", "park")
which(name == "shin")
```

