---
title: "List"
output: html_document
---

## List

```{r}
lis <- list(1, "ABC", c(1:4), matrix(1:4, ncol=2))
lis
```
> list는 벡터와 행렬과는 다르게 다른 유형의 데이터를 수용할 수 있다.

### List 생성
```{r}
li <- list (1, 1.2, 0.986)
li
```
> list 생성 후 출력하면 인덱스와 그 아래 원소값이 출력된다.

```{r}
lst <- list()
lst # 비어있는 list 생성
lst[[1]] <- 123
lst[[2]] <- "AB"
lst[[3]] <- c(1:5)
lst
```

names()
```{r}
names(lst) <- c("num","chr","vec")
lst
```
> names() 함수를 통해서 이름을 지정할 수 있으며 출력 시 $와 이름이 나타난다.

```{r}
list_name <- list(
  one = 2:6,
  two = "second",
  three = c(1,2,3),
  four = "hahaha"
)
list_name
```
> list 생성시 name 지정 가능

### list indexing
> [[]] : 하나의 원소 자체를 추출

> [] : 하나 또는 여러 개의 원소를 추출할 수 있으며 선택된 원소로 구성된 list 반환됨

```{r}
a <- list(
  a = 1:3,
  b = "a string",
  c = pi,
  d = list(-1,-5)
)

a[1] # 선택된 원소로 구성된 list 반환
a[[1]] # 해당 인덱스 원소 추출
a[["a"]] # 해당 인덱스 원소 추출
a$a # 해당 인덱스 원소 추출
```
> [[ ]]에 숫자, 이름를 주거나 $와 함께 이름을 줘도 결과가 같다.

```{r}
a[[1]][1] # 해당 인덱스 원소의 첫번째 원소 인덱스 추출
a$a[1] # 해당 인덱스 원소의 첫번째 원소 인덱스 추출

```


```{r}
a[5] # 존재하지 않는 이름의 원소 추출 시 NULL 출력
```

nulist()
```{r}
new_a <- unlist(a[1]) # nulist()를 통하여 벡터로 변환
```

```{r}
a[["c"]] <- NULL
a # a라는 list 속 c라는 원소 없애기
names(a) <- NULL
a # a라는 list의 name 없애기
```

