---
title: "Matrix & Array"
output: html_document
---

## Matrix
> Matrix(행렬)은 2차원 벡터로 정의됨

### matrix 생성
1. dim()
```{r}
x1 <- c(1,2,3,4,5,6)
dim(x1) <- c(2,3)
x1
sum(x1); min(x1);max(x1);mean(x1) # matrix의 총합, 최솟값, 최댓값, 평균 구하기
```

2. matrix()
```{r}
x2 <-matrix(1:9, nrow = 3)
x2 # ncol, nrow를 통해 생성

```

```{r}
x2 <- matrix(1:6,2,3)
x2
```
> 데이터가 열의 방향으로 채워지는게 기본값인데 행의 방향으로 채워지게 하고 싶으면 byrow=TRUE 지정

```{r}
x2 <- matrix(1:6,2,3, byrow=TRUE)
x2 # 데이터가 행의 방향으로 채워짐
```

3. rbind(), cbind()
```{r}
vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec3 <- c(7,8,9)
mat1 <- rbind(vec1,vec2,vec3)
mat1 # 행 이름 지정됨
rownames(mat1) <- NULL
mat1 # 행 이름 NULL
mat2 <- cbind(vec1,vec2,vec3)
mat2 # 열 이름 지정됨
colnames(mat2) <- NULL
mat2 # 열 이름 NULL
```

4. rownames(), colnames()
```{r}
rownames(mat1) <- c("row1","row2","row3") # 행 이름 지정
colnames(mat1) <- c("col1","col2","col3") # 열 이름 지정
mat1
```

5. rowsums(), colsums
```{r}
rowSums(mat1)
colSums(mat1)
```


### matrix indexing
```{r}
mat1[1,1] # 1행 1열
mat1[2,] # 2행
mat1[,3] # 3열
mat1[1,1,drop=F] # drop=F 로 2차원 형식 유지
mat1[2,,drop=F]
mat1[,3,drop=F]
```

**apply()**
```{r}
x3 <- matrix(1:12, nrow = 3)
x3
apply(x3, 1, sum) # 1행, 2행, 3행 값들의 합
apply(x3, 2, sum) # 1열, 2열, 3열, 4열 값들의 합
```

## Array
> 벡터는 하나의 차원을 가지며, 행렬은 두 개의 차원을 가지고 배열은 차원을 속성으로 갖는 벡터라고 정의된다.

> 일반적으로 행렬의 일반화된 데이터 형식을 베열(Array)라고 한다.

1. dim()
```{r}
a1 <- array(1:30, dim=c(2,3,5))
a1
```
- 2행 3열로 이루어진 5개의 테이블

2. array()
```{r}
a2 <- array(1:12, c(2,3,2))
a2
```
- 2행 3열로 이루어진 2개의 테이블

3. array indexing
```{r}
a1[1,3,4] # 4번째 테이블의 1행 3열 출력
a1[,,3] # 3번째 테이블 출력
a1[,2,] # 5개 테이블의 2열 출력
a1[1,,] # 5개 테이블의 1행 출력
a1[,1,2,drop=F] # 차원 유지
```

