---
title: "Vector3"
output: html_document
---

## vector indexing
> 고유의 숫자로 자신의 위치를 나타내는데 이 숫자를 인덱스라고 함.

1. vector indexing
```{r}
num <- 1:40
num # 행 앞에 첫 번째 인덱스 값을 보여줌
```
```{r}
num[5]
num[1:5]
num[c(5,5,10,10)]
num2 <- c(1,3,5)
num[num2]
num[-1:-9] # 음수로 해당 위치의 원소 제거한 벡터 생성
num[-length(num)] # 마지막 원소 제거
num[3] <- 1004; num # 3번째 위치 원소 변경 
num[c(5,7)] <- c(5000, 7000); num # 5번째, 7번째 원소 변경
```

2. which() 
```{r}
rainfall <- c(21.6, 23.6, 45.8, 77.0, 102.2, 133.3,327.9, 348.0, 137.6, 49.3, 53.0, 24.9)
rainfall > 100
rainfall[rainfall > 100]
which(rainfall > 100)
month.name[which(rainfall > 100)]
month.abb[which(rainfall > 100)]
month.korname <-c("1월","2월","3월","4월","5월","6월","7월","8월","9월","10월","11월","12월")
month.korname[which(rainfall > 100)]
which.max(rainfall)
which.min(rainfall)
month.korname[which.max(rainfall)]
month.korname[which.min(rainfall)]
```
> which() 함수는 논리값을 인수로 받아서 TRUE인 위치의 인덱스를 반환

## vectorized operation
```{r}
2 ^ 10 # 거듭제곱
10 %% 3 # 나머지
10 %/% 3 # 몫
c(1,2,3) + c(4,5,6) # 1+4, 2+5, 3+6
y <- c(0,25,50,75,100)
z <- c(50, 50, 50, 50,50)
y == z
y != z
y > z
y < z
y >= z
y <= z
y == 50 # c(50, 50, 50, 50, 50)
y > 50
```

